name: Sync Fork

on:
  schedule:
    - cron: '0 11 * * *' # every Day at 11 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: honjes
          base: master
          head: master
